### ISSUE TITLE
Question: how to use the Passatutto decoy generation

### ISSUE THREAD

**Issue by asmirn1** [sirius-ms/sirius#129]
Hi,

I'm trying to run Sirius for the first time and have a few questions about it.

I want to generate decoy libraries according to this paper: https://www.nature.com/articles/s41467-017-01318-5. 

After some searching online, I read the Sirius would generate a decoy library with the command: 

sirius -i spectral-lib -o output  formula passatutto  

I was able to run it on my .mgf file and got some output (Sirius project folder). However, I'm not sure what to do next to export the decoy library to .mgf format. The tutorial doesn't say much other than the command above.

I wonder if you could help me with running the passatutto algorithm properly?

Thank you,

Alex

**Comment by mfleisch** [comment]
Hey,
in case this is still relevant for you: 
In SIRIUS 5 there are no additional tools to convert the library to mgf. Sirius just provides the decoy spectra as `.ms` files in the output project and the fragmentation tree as json. Converting the `.ms` file to an `mgf` has unfortunately  to be done by yourself.

In SIRIUS 6 Passatutto is not yet available but will be deeply integrated in SIRIUS in the future. 

I am closing this issue since it might already be stale and the question has been answered.
