### ISSUE TITLE
Export Issues with Sirius 5.8.3

### ISSUE THREAD

**Issue by hfchang12** [sirius-ms/sirius#137]
Good evening,

I am currently facing challenges with exporting files in Sirius 5.8.3 on Mac. Specifically, I am unable to export the following three files:
id/formula_candidate.tsv 
id/structure_candidate.tsv
canopus_summary.tsv

Despite executing the provided command:
-o {odir} -i {mgf} formula --profile qtof --database all '\
        ' --candidates 50 --ppm-max-ms2 10 '\
        ' zodiac --thresholdFilter 0.98 fingerprint structure --database all canopus write-summaries'\

The exported files I currently have are:
canopus_compound_summary.tsv
canopus_formula_summary.tsv
canopus_neg.tsv
canopus_npc_neg.tsv
canopus_npc.tsv
canopus.tsv
compound_identifications.tsv
csi_fingerid_neg.tsv
csi_fingerid.tsv
formula_identifications.tsv
report.mztab

I am seeking guidance on how to rectify this issue and successfully export the three mentioned files. Your assistance in this matter would be highly appreciated.

Thank you in advance for your time.

**Comment by mfleisch** [comment]
Hey,
the command works as expected for me.
I get: 
- `id/formula_candidate**s**.tsv`
- `id/structure_candidate**s**.tsv`

Are you just missing the `s`?

`canopus_summary.tsv` are not expected to exist. Only `canopus_compound_summary.tsv`
and  `canopus_formula_summary.tsv` are expected.  Could be that `canopus_formula_summary.tsv` was called `canopus_summary.tsv` in the past. 

I am closing this since it might already been stale due to the long response time. Feel free to reopen in case you still have issues with the export. If so please provide some example data.
