### ISSUE TITLE
changing configuration

### ISSUE THREAD

**Issue by hbckleikamp** [sirius-ms/sirius#145]
Dear developers,

This is not really a bug, but I was wondering if you could help me.

I am using Sirius for molecular formuala prediction, and I want to be quite stringent with isotopic envelopes and enforce only [M+H]+ adducts. Each feature has a compound file: compound.config

Which lists certain parameters that I would like to edit globally before running formula prediction (for example):
AdductSettings.detectable = [M+H]+,[M+K]+,[M+Na]+,[M+H-H2O]+,[M+H-H4O2]+,[M+NH4]+,[M-H]-,[M+Cl]-,[M-H2O-H]-,[M+Br]-
ms1.relativeIntensityError = 0.08

Should I add these in the sirius.bat file by adding a line that specifies these arguments in SIRIUS_OPTS?
@rem Execute sirius
"%JAVA_EXE%" %DEFAULT_JVM_OPTS% %JAVA_OPTS% %SIRIUS_OPTS%  -classpath "%CLASSPATH%" "%MAIN_CLASS%" %*

Thanks,
Hugo.

**Comment by mfleisch** [comment]
Hey Hugo,
i know it has been a while since this was asked.


There are two scenarios we have to deal with here:

1. If your input data e.g. and `mgf` file already contains a specific adduct different from [M+H]+ you would need to replace them in the input. But the question would be why would you do this since if the preprocessing assigned an adduct it is very likely that it is more reasonable than  just guessing [M+H]+.

2. the adduct in the input is unknown ( [M+?]+). In that case you need to change the detectable and fallback adduct parameter when calling the cli.   This can be achieved by using the `--adducts-considered` parameter of the[ formula subtool](https://v6.docs.sirius-ms.io/cli/#SIRIUS-formulas).

I am closing this since it is likely already stale. Feel free to reopen if this does not answer the question.
