### ISSUE TITLE
Need help for Sirius 5

### ISSUE THREAD

**Issue by ValentinCledassou** [sirius-ms/sirius#163]
Hello,

I have isolated some metabolites of interest from mzML files with xcms and camera tools. I have also three DDA files corresponding to the MS1 and MS2 spectra of these mzML files.

When I  import my three raw DDA files into Sirius 5 in order to analyze the spectra of my metabolites of interest (formula and compound prediction), I have the choice between align or not my runs. 
When I align my DDA files, I find my metabolites of interest that I have isolated in the previous steps (xcms and camera). But when I don't align my runs, many of my metabolites of interest disappear.

So should i align or not align my runs when I import my DDA files into Sirius ?

**Comment by mfleisch** [comment]
Hey,
yes aligning is right option. Further I would recommend upgrading to SIRIUS 6 since the worked a lot  on the preprocessing there. 

I am closing the issue since there is nothing to do from development side. For further discussion feel free to join our new gitter community https://matrix.to/#/#sirius-ms:gitter.im.
