### ISSUE TITLE
No database matches when running CSI finger ID

### ISSUE THREAD

**Issue by vdiazri** [sirius-ms/sirius#164]
Hello!

I am not sure whether I am doig something wrong, so I am reaching out to get some guidance.

I am trying to check if I have any additional database matches on a dataset I already ran on the GNPS, for this prupose I am using sirius 6.0.0, checked the connection settings and seem to be working fine and as an input, the same .mgf file I used for the molecular networks I have. After  importing my .mgf,  I  ran the SIRIUS-Molecular formula identificarion, CSI finger ID-fingerprint prediction and CSI finger ID -Structure database search but when checking my resluts tabs, I see computations for the formula identification modules  and no matches on the database search tabs.

When I realised this, I included the GNPS database (where I know I have matches) and recomputed the tasks but still have no matches against the libraries in sirius.

Is there any chance I am  doing anything wrong?  If any of you could give me some guidance, it would be greatly appreciated.

Please see the sirius project +mgf files attached.
[fracciones_5.zip](https://github.com/user-attachments/files/15804306/fracciones_5.zip)

**Comment by mfleisch** [comment]
Hey I had a quick look into your data. With 6.0.5 the data imported fine and I was able to perform an analyses.
However the results look indeed not very promising and many feature cannot even be annotated.

What I noticed:
- during import many features are skipped since they do not contain any non empty spectra
- often there is no ms1 spectrum which reduces accuracy of formula identification
- relatively often there is no ms/ms spectrum available which is mandatory for structure elucidation with SIRIUS.
- there are also quite some features with  ms/ms that have only < 3 decomposable peaks which is not enough information to perform an analysis.

This all looks like that there is something going wrong during your feature detection and/or your mgf export.

I am closing this issue since there is nothing to do from development side. 
For further discussion please join our new gitter community: https://matrix.to/#/#sirius-ms:gitter.im
