### ISSUE TITLE
Summary export discrepancies

### ISSUE THREAD

**Issue by djb561** [sirius-ms/sirius#181]
When exporting the summaries (all hits selected), the summary files generated are dependant on how the data is sorted (by RT, name, mass etc). If sorted by RT, there only seems to be 10-15 features exported, while when sorted by confidence, it is around 500 features exported. Version 6.02

**Comment by typewritermonkey** [comment]
Yes I just noticed this as well. It's only exporting a small fraction of my summaries even when I tick the box for "all hits"

**Comment by andriikovalov** [comment]
Sounds like summary export is breaking on a certain record, and depending on sorting it might be near the top or further down. Could you please check the log for errors? If you are using GUI, there is a "Log" button in the top row on the right. Open it after the summary export, scroll down, and check the last 50 or so lines. If there is an error message with a stack trace, please post it here, this would help investigate the issue

**Comment by typewritermonkey** [comment]
Aug 23, 2024 7:16:48 PM org.dizitart.no2.NitriteDatabase close
INFO: Nitrite database has been closed successfully.
Aug 23, 2024 7:16:48 PM org.dizitart.no2.NitriteDatabase close
INFO: Nitrite database has been closed successfully.
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.ms.frontend.Run parseArgs
INFO: Running with following arguments: [summaries, --output=C:\Users\Dan\Desktop\MZMine 4.2 Projects\Files for Sirius\sirius summaries, --full-summary, --top-hit-adduct-summary, --top-hit-summary, --top-k-summary=1]
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.ms.frontend.Run parseArgs
INFO: Running with following arguments: [summaries, --output=C:\Users\Dan\Desktop\MZMine 4.2 Projects\Files for Sirius\sirius summaries, --full-summary, --top-hit-adduct-summary, --top-hit-summary, --top-k-summary=1]
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.ms.frontend.Run parseArgs
INFO: Running with following arguments: [summaries, --output=C:\Users\Dan\Desktop\MZMine 4.2 Projects\Files for Sirius\sirius summaries, --full-summary, --top-hit-adduct-summary, --top-hit-summary, --top-k-summary=1]
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.ms.backgroundruns.BackgroundRuns lambda$submitRunAndLockInstances$15
INFO: Locking Instances for Computation...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.ms.backgroundruns.BackgroundRuns lambda$submitRunAndLockInstances$15
INFO: Locking Instances for Computation...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.ms.backgroundruns.BackgroundRuns lambda$submitRunAndLockInstances$15
INFO: Locking Instances for Computation...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.ms.backgroundruns.BackgroundRuns lambda$submitRunAndLockInstances$15
INFO: ...All instances locked!
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.ms.backgroundruns.BackgroundRuns lambda$submitRunAndLockInstances$15
INFO: ...All instances locked!
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.ms.backgroundruns.BackgroundRuns lambda$submitRunAndLockInstances$15
INFO: ...All instances locked!
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Start Computation...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing summary files...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '2'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '2'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '5'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '5'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '4'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '4'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '10'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '10'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '18'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '18'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '36'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '36'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '37'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '37'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '43'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '43'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '39'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '39'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '66'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '66'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '74'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '74'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '76'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '76'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '81'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '81'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '83'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '83'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Writing Feature '84'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <39>[NoSqlSummarySubToolJob-39] Writing Feature '84'...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logError$2
SEVERE: <39>[NoSqlSummarySubToolJob-39] Failed!
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "java.util.Map.get(Object)" is null
	at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlStructureSummaryWriter.writeStructureCandidate(NoSqlStructureSummaryWriter.java:110)
	at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlSummarySubToolJob.compute(NoSqlSummarySubToolJob.java:221)
	at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlSummarySubToolJob.compute(NoSqlSummarySubToolJob.java:62)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:124)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Flushing Results to disk in background...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Results flushed!
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logError$2
SEVERE: <40>[BackgroundRunJob-40] Failed!
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "java.util.Map.get(Object)" is null
	at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlStructureSummaryWriter.writeStructureCandidate(NoSqlStructureSummaryWriter.java:110)
	at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlSummarySubToolJob.compute(NoSqlSummarySubToolJob.java:221)
	at de.unijena.bioinf.ms.frontend.subtools.summaries.NoSqlSummarySubToolJob.compute(NoSqlSummarySubToolJob.java:62)
	at de.unijena.bioinf.jjobs.BasicJJob.call(BasicJJob.java:124)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Unlocking Instances after Computation...
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] All Instances unlocked!
Aug 23, 2024 7:17:08 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Freeing up memory...
Aug 23, 2024 7:17:09 PM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFO: <40>[BackgroundRunJob-40] Memory freed!

**Comment by typewritermonkey** [comment]
Not sure what that stuff means but I posted it all just in case!

**Comment by andriikovalov** [comment]
Thanks! Exactly what I need :)

**Comment by typewritermonkey** [comment]
Any luck resolving this yet?

**Comment by andriikovalov** [comment]
Yes, sorry for a delay. This is going to be fixed in the next minor release, in a week or so. I'll ping you when it is out

**Comment by andriikovalov** [comment]
@typewritermonkey @djb561 fixed in version 6.0.5
