### ISSUE TITLE
ftree-export command not available

### ISSUE THREAD

**Issue by adriaolomi** [sirius-ms/sirius#191]
Hi,

I was checking the set of standalone CLI tools and I was interested on using the fragmentation tree export tool (ftree-export). However, it seems that is not available using the version that I have. When I type "sirius --help" I see some standalone tools but not the export option. Just in case, I've run "sirius install-autocompletion" but still not appearing. 

I'm using Sirius v./ 6.0.2 and Ubuntu 22.04.1 OS.

**Comment by mfleisch** [comment]
Hey,
the fragmentation tree export cli tool is no longer available with sirius 6.
But you can access/export all this information using the new API, see here for details: https://v6.docs.sirius-ms.io/quick-start/#API

I close the issue since there is nothing to do from development side. 
I case you need help feel free to  join our new `sirius-ms` community on Gitter/Matrix: https://matrix.to/#/#sirius-ms:gitter.im .
