### ISSUE TITLE
Quantification Feature table .csv empty

### ISSUE THREAD

**Issue by paula-mor** [sirius-ms/sirius#201]
Hi,

After processing my data in MZmine4.2.0 and running it on SIRIUS 5.8.6, I do get the .mgf file correctly when exporting for FBMN, however, the .csv file containing the feature table appears completely empty.
Could it be due to the parameters apply or might be a bug?
![image](https://github.com/user-attachments/assets/4391d686-e8ab-4dcf-acd5-f46f3c475264)

Many thanks in advance!

**Comment by mfleisch** [comment]
Hey,
the FBMN export in SIRIUS is only working if you import `.mzml` and perform the preprocessing with SIRIUS. Otherwise (e.g. when importing `mgf`), quantitative information is just not available in the input.

When doing the preprocessing in MZmine the workflow is slightly different. 

1. mzMine -> export for FBMN -> GNPS
2. mzMine ->  export to SIRIUS ->  SIRIUS
3. SIRIUS preserves the features IDs given by MZmine in the summary files as `mappingFeatureId`, so you can map the features to your molecular networks created on GNPS.

Closing since there is nothing to do from development side. For further discussions feel free to join the sirius-ms community on gitter: https://matrix.to/#/#sirius-ms:gitter.im
