### ISSUE TITLE
Mistakes in fragmentation tree and output spectra labels

### ISSUE THREAD

**Issue by nirshahaf** [sirius-ms/sirius#29]
Hi,

There is a possible bug in the output format of the fragmentation tables of the Sirius output
(the parent MF, C42H42O19 is correct):
As fragments and heavier isotopic peaks are co-occurring in the data, I would expect them to
be labelled according, however in the output table the isotopes are labelled as independent 
chemical entities, which are wrongly labelled as a +[H] of the monoisotopic mass, see:

![image](https://user-images.githubusercontent.com/13019561/110233965-67b4ec00-7f30-11eb-9b86-e8ac2f5bb582.png)

Additionally, the corresponding fragmentation tree seems mistaken - with the [M+1]+ and [M+2]+ taken as distinct
fragments and become parents of subsequent sub-trees:

![image](https://user-images.githubusercontent.com/13019561/110234050-122d0f00-7f31-11eb-8efb-fc9882982d1b.png)

**Comment by kaibioinfo** [comment]
Woah, this is a mean one: the subtree of [C42H41O18 + 1] looks perfect: several hexose moieties, water losses - sure it gets high score and is picked, although the "OH" loss and the "O" loss are both strange.

By default, there is no special treatment of isotope peaks. You have to enable this option explicitely. In the CLI you can do that with the `--IsotopeMs2Settings SCORE` option. Instead of SCORE you can also write FILTER (not implemented yet for some reason, I already added a ticket) and IGNORE (default). 

Just a few words to the Isotope detection in MS/MS: The idea of the FILTER option is to just remove isotope peaks before starting computation. Its a very simple heuristic that checks for monotonic decreasing peaks with the right mass following high intensive peaks and removes them. It is not enabled by default, because isotope peaks usually only appear for specific instruments (like Bruker) and setups (like DIA). So we do not want to accidentally remove real signal peaks on an Agilent Q-ToF where we do not see isotope peaks in MS/MS anyways. 
The SCORE option however integrates the isotope peaks into the optimization problem. This makes the optimization problem much harder (because isotope peaks violate the assumption that parent peaks do always have larger masses than their children; this assumption is necessary for many tricks to speed-up the computation). Thus, expect that computation will take more time when enabling this option. Second problem: Isotope peaks in MS/MS can look very different. To be honest, I have never seen so clean isotope peaks as in your example above. Usually, their intensities are totally disturbed and "strange". This is because the isotope intensity in MS/MS depends totally on the instrument and the isolation window setting. It is really hard to find some general setup or scoring for isotopes that work for all kind of instruments and isolation windows. In DIA, of course, you have perfect isotopes. But so far we had rather bad experiences with DIA methods: they produce WAY less fragments than the DDA and a lot of chimeric peaks from isobar compounds. Thus, I would not recommend to use SIRIUS on DIA, without tuning it on DIA beforehand.
Which kind of instrument/setup did you used for the measurement above?

**Comment by nirshahaf** [comment]
Hi and thanks!

It seems that the '--IsotopeMs2Settings' is still not a valid option in the current version (4.6.1)

Regarding DIA, we are using the "Ramp" (MS^E) option on the popular and trusty Waters Synapt-G1 instrument. Following earlier discussions we increased the ionization energy values and actually get nice fragmentation patterns for most compounds - at least in injections of chemical standards - such as the one in the example above. On more modern Waters instruments, BTW, we get many more fragments - especially in the lower mass ranges. The isotopic peaks are usually measured well also in samples of biological matrices - however the co-occurrence of unrelated peaks is a curse which is difficult to dispel - I am actually hoping that Sirius can aid by removing non-relevant fragments and leaving a much cleaner spectra. Visually, this strategy seems to be working well (disregarding the MS2 isotopes) but since we have no a-priory knowledge about the fragmentation patterns of most of these chemical standards, nor a reliable external reference, I don't see a good way to systematically estimate the performance of the virtual fragmentation with this data. I assume that the best solution for the correct formula does detect and correctly annotates the most meaningful fragments.
meaningful fragments.

**Comment by nirshahaf** [comment]
Hi, from which version is the '--IsotopeMs2Settings' option implemented?

**Comment by nirshahaf** [comment]
Hi,

I tried the suggested options ('FILTER' or 'SCORE') - but both resulted in the same wrong tree (V4.6.1 CLI, V4.8.2 GUI):

![image](https://user-images.githubusercontent.com/13019561/124782885-451df880-df4d-11eb-8100-e2314fa1a853.png)

...it also seems that 'FILTER' is not yet implemented (?) I also noticed the 'QTOF isotopes' present - but selecting it did not change the results...

**Comment by nirshahaf** [comment]
BTW, is there an option to specify 'config' parameters in a persistent manner, e.g., by editing the /.sirius-4.x/custom.config file?

**Comment by mfleisch** [comment]
> BTW, is there an option to specify 'config' parameters in a persistent manner, e.g., by editing the /.sirius-4.x/custom.config file?

Yes, you should be able to achieve exactly this by using the `custom.config` file.

**Comment by chrispook** [comment]
Hello, I am trying out SIRIUS on my DIA data as an alternative to MS-FINDER, which can be very slow (weeks) with thousands of features. Can you clarify what you mean below by "tuning" SIRIUS on DIA data?

> Second problem: Isotope peaks in MS/MS can look very different. To be honest, I have never seen so clean isotope peaks as in your example above. Usually, their intensities are totally disturbed and "strange". This is because the isotope intensity in MS/MS depends totally on the instrument and the isolation window setting. It is really hard to find some general setup or scoring for isotopes that work for all kind of instruments and isolation windows. In DIA, of course, you have perfect isotopes. But so far we had rather bad experiences with DIA methods: they produce WAY less fragments than the DDA and a lot of chimeric peaks from isobar compounds. Thus, I would not recommend to use SIRIUS on DIA, without tuning it on DIA beforehand. Which kind of instrument/setup did you used for the measurement above?



Thanks. Chris

**Comment by AharoniLab** [comment]
Hi Chris, referring to "tuning" Sirius to DIA data I would look at two parameters: a) the MS2 mass measurement accuracy which should reflect your instrument's performance; b) the isotopic pattern score multiplier which is in the config file and should reflect your confidence in the accuracy of isotope abundance measurements. Together, these two parameters can help float the true chemical formula annotations towards higher ranks, which later propagates to better DB annotations. 
To my best knowledge, neither the 'SCORE' nor the 'FILTER' Sirius options work and the MS2 isotopes detected in DIA remain "as-is" - that is at least with all the versions that I've used. 
*Word of caution: some software packages distort the isotopic pattern abundance measurement during peak integration and you might want to check with Hiroshi Tsugawa regarding how MS-Dial does. 
HTH, Nir.
