### ISSUE TITLE
Versioned *.ms file format

### ISSUE THREAD

**Issue by sneumann** [sirius-ms/sirius#74]
Hi, 
it would be great to provide a version number of the file format of a *.ms file in one of the next iterations. 
Yours, 
Steffen

**Comment by mfleisch** [comment]
Hey Steffen,
sorry we somehow forget about this issue.

The `*.ms` was never meant to become an official/standardized format since there are already quite a few formats (e.g. `.mgf`, `.msp` , `.mat` or the  `massbank`) out there that carry similar information and are also supported by SIRIUS.  

The `.ms` format should be seen as an SIRIUS internal file format we use to quickly try out new things without having to care too much about versioning, vocabulary, standardization and backward compatibility.  

So I don't think we will be able to version this format properly in the future.
