### ISSUE TITLE
Possible to compute for specified list of a few hundred compounds?

### ISSUE THREAD

**Issue by meenachakra** [sirius-ms/sirius#87]
Hello! Thank you for the great tool. If possible, I wish to speed up the computation in the GUI by filtering to a list of a few hundred specific molecules I'm interested in (I have a list of IDs). Is that possible? Thanks in advance for your help!

**Comment by JethroHemmann** [comment]
I would also be interested in that feature, potentially also filtering using a list of m/z and rt values. (maybe using the CLI)

**Comment by mfleisch** [comment]
Hey,
> I would also be interested in that feature, potentially also filtering using a list of m/z and rt values. (maybe using the CLI)

This should already be possible in SIRIUS 5.  Besides the Text Search field in the compound list (left most panel) there is a button `...` that opens advanced search features. You can then compute results on the filtered list using compute all.
The CLI contains a stand alone subtool called `project-space` which can be used to filter results from the project space. But most CLI users just filter the project directory using custom scripts since the data of each feature/compound is self contained in separate subdirectories.

**Comment by mfleisch** [comment]
> Hello! Thank you for the great tool. If possible, I wish to speed up the computation in the GUI by filtering to a list of a few hundred specific molecules I'm interested in (I have a list of IDs). Is that possible? Thanks in advance for your help!

This is currently not possible in the GUI but should work with the filter options of the `project-space` CLI subtool described above.  

Such a feature might be available in the midterm when updating the persistence layer of SIRIUS. I Added your request to our internal feature request list.

**Comment by JethroHemmann** [comment]
> Hey,
> 
> > I would also be interested in that feature, potentially also filtering using a list of m/z and rt values. (maybe using the CLI)
> 
> This should already be possible in SIRIUS 5. Besides the Text Search field in the compound list (left most panel) there is a button `...` that opens advanced search features. You can then compute results on the filtered list using compute all. The CLI contains a stand alone subtool called `project-space` which can be used to filter results from the project space. But most CLI users just filter the project directory using custom scripts since the data of each feature/compound is self contained in separate subdirectories.

Thanks for your reply! Filtering the project-space directory using a script seems a viable solution to me.
