### ISSUE TITLE
missing features in Sirius-summary (time-out ?)

### ISSUE THREAD

**Issue by eimichae85** [sirius-ms/sirius#96]
Dear Sirius team,

I recently imported an mgf file into Sirius which contained data on about 5000 features.
I then submitted my features to Sirius, selected my parameters (only selecting the most realistic parameters to decrease computing time) and ran/computed the features via Sirius. After ca. 2 days or so the analyses was completed and I exported the summaries to a csv. File.

However, I quickly realized that information of about 2000 featuers was missing. i.e. the csv. File contained only information of about 2500 features. The other features were not listed on the file.
What does this mean? Could these features not be identified and where therefore kicked-out of the summary?
Or was the computation somehow “timed-out” (as mentioned in the FAQ section) and shut down after a specific amount of time (I did not exclude compounds with a mass higher than 850Da). Where could I find these settings?

Thanks a lot and sorry for the greenhorn questions!
Mike

**Comment by mfleisch** [comment]
Hey Mike,
I just copied my answer from our email correspondence in case somebody else has the same question.

per default computation should not time out. The settings for the timeout are part of the SIRIUS step in the compute dialog.

There could be multiple reasons why SIRIUS does not provide an annotation. Most likely because the MS/MS spectrum does not contain enough information for a meaningful fingerprint prediction. SIRIUS needs to be able to explain at least 3 peaks of the MS/MS with the fragmentation tree. otherwise it will not predict a fingerprint.

**Comment by karlssoc** [comment]
I have a question regarding timeout for tree and compound. I assume it depends on processor speed, but what are resonable timeout values? Do you lose many identifications with for example 30 s timeout values?

**Comment by mfleisch** [comment]
30s sounds reasonable but you will definitely lose quite a few larger compounds >850 dalton with this timeout. 
I would rather think about using timeout that just filters our the very bad compounds that take many minutes or hours and block your whole analysis. 

Closed since there is nothing to do from development side. For further discussion feel free to join our new gitter community: https://matrix.to/#/#sirius-ms:gitter.im
